# Generated by Django 4.2.5 on 2023-09-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cod_reservation',
            field=models.CharField(default='PRT001', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
