# Generated by Django 4.2.5 on 2023-09-23 01:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_cod_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cod_reservation',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
